import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const palette = JSON.parse(await readFile(path.join(root, 'lib/workbench/theme-palette.json'), 'utf8'));
const lines = ['/* Generated by npm run theme:sync. Edit lib/workbench/theme-palette.json. */', ':root {'];
for (const [key, [light, dark]] of Object.entries(palette)) {
  lines.push(`  --theme-light-${key}: ${light};`, `  --theme-dark-${key}: ${dark};`, `  --theme-${key}: light-dark(${light}, ${dark});`);
}
lines.push('}', ':root { color-scheme: dark; }', ':root[data-theme="light"] { color-scheme: light; }', ':root[data-theme="dark"] { color-scheme: dark; }', '');
const output = lines.join('\n');
for (const name of ['app/theme-tokens.css', 'Tools/SpritePipeline/sprite_pipeline/static/theme-tokens.css']) {
  const file = path.join(root, name);
  if (process.argv.includes('--check')) {
    if (await readFile(file, 'utf8') !== output) throw new Error(`${name} is stale; run npm run theme:sync`);
  } else await writeFile(file, output);
}
